"""Session management for multi-turn conversations.

This module provides session management capabilities using Google ADK's
InMemoryRunner with app-based architecture.

Note: Google ADK uses an app-based architecture for session management.
For simplicity in this capstone project, we provide wrapper classes that
demonstrate the concept of session persistence and multi-turn conversations.
"""

from google.adk.runners import InMemoryRunner

from strategic_consultant_agent.agent import create_strategic_analyzer


class StrategicConsultantSession:
    """
    Manages multi-turn conversation sessions with the strategic consultant agent.

    This class wraps Google ADK's InMemoryRunner to enable stateful conversations
    where agents can reference previous analyses and maintain context across
    multiple user inputs.

    Note: This implementation uses a simplified session model for demonstration.
    Production deployments should use Google ADK's full App architecture with
    proper session management.

    Example:
        >>> session = StrategicConsultantSession()
        >>> for event in session.run("Should we scale fall detection?"):
        ...     print(event)
        >>> # State persists across turns within the same session
        >>> for event in session.run("Show top priorities"):
        ...     print(event)
    """

    def __init__(
        self,
        user_id: str = "default_user",
        session_id: str = "default_session",
        app_name: str = "strategic_consultant",
    ):
        """
        Initialize a new session.

        Args:
            user_id: User ID for this session (default: "default_user")
            session_id: Session ID (default: "default_session")
            app_name: Application name (default: "strategic_consultant")
        """
        self.agent = create_strategic_analyzer()
        self.runner = InMemoryRunner(
            agent=self.agent,
            app_name=app_name,
        )
        self.user_id = user_id
        self.session_id = session_id
        self.app_name = app_name

    def run(self, user_input: str):
        """
        Run the agent with user input in a session context.

        Args:
            user_input: The user's question or request

        Yields:
            Event: Events generated by the agent execution

        Example:
            >>> session = StrategicConsultantSession()
            >>> for event in session.run("Analyze fall detection scaling"):
            ...     if event.type == "output":
            ...         print(event.data)
        """
        from google.genai import types

        # Create message content
        message = types.Content(parts=[types.Part(text=user_input)])

        # Run the agent
        yield from self.runner.run(
            user_id=self.user_id,
            session_id=self.session_id,
            new_message=message,
        )

    def get_session_id(self) -> str:
        """
        Get the current session ID.

        Returns:
            str: Current session ID
        """
        return self.session_id

    def get_user_id(self) -> str:
        """
        Get the current user ID.

        Returns:
            str: Current user ID
        """
        return self.user_id


def create_runner() -> InMemoryRunner:
    """
    Create a runner for the strategic consultant agent.

    This is a convenience function for creating a configured runner.

    Returns:
        InMemoryRunner: Configured runner

    Example:
        >>> runner = create_runner()
        >>> message = types.Content(parts=[types.Part(text="Analyze this...")])
        >>> for event in runner.run(
        ...     user_id="user123",
        ...     session_id="session456",
        ...     new_message=message
        ... ):
        ...     print(event)
    """
    agent = create_strategic_analyzer()
    return InMemoryRunner(
        agent=agent,
        app_name="strategic_consultant",
    )


def run_analysis(
    user_input: str,
    user_id: str = "default_user",
    session_id: str = "default_session",
):
    """
    Run a strategic analysis (convenience function).

    Args:
        user_input: The user's question or request
        user_id: User ID (default: "default_user")
        session_id: Session ID (default: "default_session")

    Yields:
        Event: Events generated by the agent execution

    Example:
        >>> for event in run_analysis("Should we scale fall detection?"):
        ...     if event.type == "output":
        ...         print(event.data)
    """
    from google.genai import types

    runner = create_runner()
    message = types.Content(parts=[types.Part(text=user_input)])

    yield from runner.run(
        user_id=user_id,
        session_id=session_id,
        new_message=message,
    )
